#!/usr/bin/env python3
"""
Generate sin/cos lookup tables for FOC controller
Output: Verilog module with BRAM-based LUTs
"""

import math
import sys

def generate_sincos_lut(table_size=256, output_file="sincos_lut.v"):
    """
    Generate sin/cos lookup tables
    
    Args:
        table_size: Number of entries (256 = 8-bit address)
        output_file: Output Verilog file
    """
    
    # Generate sin/cos values
    sin_values = []
    cos_values = []
    
    for i in range(table_size):
        angle = 2 * math.pi * i / table_size
        sin_val = math.sin(angle)
        cos_val = math.cos(angle)
        
        # Scale to 16-bit signed integer (-32768 to 32767)
        sin_int = int(sin_val * 32767)
        cos_int = int(cos_val * 32767)
        
        # Clamp to valid range
        sin_int = max(-32768, min(32767, sin_int))
        cos_int = max(-32768, min(32767, cos_int))
        
        sin_values.append(sin_int)
        cos_values.append(cos_int)
    
    # Generate Verilog module
    with open(output_file, 'w') as f:
        f.write(f"""// Sin/Cos Lookup Table for FOC Controller
// Auto-generated by gen_sincos_lut.py
// Table size: {table_size} entries
// Input: 16-bit angle (0-65535 = 0-360°)
// Output: 16-bit signed sin/cos (-32768 to 32767)

module sincos_lut (
    input  wire        clk,
    input  wire [15:0] angle,      // 0-65535 = 0-360°
    output reg  [15:0] sin_out,    // Signed 16-bit
    output reg  [15:0] cos_out     // Signed 16-bit
);

    // Use top {int(math.log2(table_size))} bits as LUT address
    wire [7:0] lut_addr = angle[15:8];  // Top 8 bits for 256-entry LUT
    
    // Sin lookup table (BRAM)
    always @(posedge clk) begin
        case (lut_addr)
""")
        
        # Write sin LUT cases
        for i, sin_val in enumerate(sin_values):
            # Convert to 16-bit hex (handle negative numbers)
            sin_hex = sin_val & 0xFFFF
            f.write(f"            8'd{i}: sin_out <= 16'h{sin_hex:04X};\n")
        
        f.write(f"""            default: sin_out <= 16'h0000;
        endcase
    end
    
    // Cos lookup table (BRAM)
    always @(posedge clk) begin
        case (lut_addr)
""")
        
        # Write cos LUT cases
        for i, cos_val in enumerate(cos_values):
            # Convert to 16-bit hex (handle negative numbers)
            cos_hex = cos_val & 0xFFFF
            f.write(f"            8'd{i}: cos_out <= 16'h{cos_hex:04X};\n")
        
        f.write(f"""            default: cos_out <= 16'h0000;
        endcase
    end

endmodule
""")
    
    print(f"Generated {output_file} with {table_size} entries")
    print(f"Sin range: [{min(sin_values)}, {max(sin_values)}]")
    print(f"Cos range: [{min(cos_values)}, {max(cos_values)}]")

if __name__ == "__main__":
    generate_sincos_lut(table_size=256, output_file="sincos_lut.v")
